# Generated by Django 4.1.5 on 2023-01-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("getlink_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"verbose_name": "Page List", "verbose_name_plural": "Pages List"},
        ),
        migrations.RenameField(
            model_name="page", old_name="data_created", new_name="created",
        ),
        migrations.RenameField(
            model_name="page", old_name="data_updated", new_name="updated",
        ),
    ]
