# Generated by Django 4.1.5 on 2023-01-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "getlink_app",
            "0002_alter_page_options_rename_data_created_page_created_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "verbose_name": "Страница id, slug, namespace",
                "verbose_name_plural": "Страницы id, slug, namespace",
            },
        ),
        migrations.RenameField(
            model_name="page", old_name="created", new_name="data_created",
        ),
        migrations.RenameField(
            model_name="page", old_name="updated", new_name="data_updated",
        ),
    ]
